### PR TITLE
Switch from 'Amy' to 'AMY'

### LINKED ISSUE #328: Change name of app
Having the same name for a person and the app is confusing, especially since we both work in the same areas. Suggest "amybot" for the app.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
We're switching from 'Amy' to 'AMY' to distinguish between real people and this project.

I think we have a consensus to leave 'amy' as the name for the eventual packages (PyPI / NPM), and 'AMY' for the project.

This resolves #328.

### CODE REVIEW

**Comment by gvwilson** [comment]
Mmm.. I like aMY, just to be conTRARY, but I can lIVE wITH tHIS.

**Comment by pbanaszkiewicz** [comment]
Honestly I had no idea that https://github.com/swcarpentry/amy/commit/25e67c0ebf3afd9cb6d60f1b2d0592ad12c7e854 was "aMY". I can rebase, if you're more decided on aMY than AMY.

**Comment by gvwilson** [comment]
I'm mostly trolling - I'll sleep on it and we'll figure it out 
tomorrow.  bUT I tHINK iT wOULD bE kIND oF cOOL.

**Comment by pbanaszkiewicz** [comment]
:-)

**Comment by gvwilson** [comment]
If you can update this, we can merge it - @amyrbrown would be very grateful if we switched to AMY in all caps.  I will then update the logo...

**Pull request merged**
