### PR TITLE
 Included notes field on instructor profile update form

### PR DESCRIPTION
**Pull request by shubhsingh594**
Fixes https://github.com/swcarpentry/amy/issues/659

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Thanks for your PR, @shubhsingh594. Unfortunately it's still missing "Notes" field on the form accessible by normal users (see https://github.com/swcarpentry/amy/pull/717#issuecomment-191087974). Please update accordingly.

Your change will break tests, so you'll have to fix them too.

**Comment by shubhsingh594** [comment]
@pbanaszkiewicz  hi,

i noticed that forms.ProfileUpdateRequestFormNoCaptcha , is using ' exclude ' instead of fields. so Notes should get included automatically . i also checked and i am able to use the notes textfield, by going to this url - http://127.0.0.1:8000/workshops/update_profile/

**Comment by pbanaszkiewicz** [comment]
@shubhsingh594 I was wrong, you're right; the field appears where it should be.

Please wrap the field's contents with `<pre>` tag and I'll merge this.

Thanks & sorry!

**Comment by pbanaszkiewicz** [comment]
Thanks a lot for your contribution, @shubhsingh594!

**Pull request merged**
