### PR TITLE
Make common actions more accessible in the menu.

### PR DESCRIPTION
**Pull request by gvwilson**
This turns Sites, Events, and Persons into drop-down menus that go to "show all X" and "add new X".

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Why do you need them this way?

**Comment by gvwilson** [comment]
I find the workflow easier, particularly when I want to add a new event, 
realize the site isn't set up, need to add a new site, then want to go 
back to adding a new event.

**Comment by pbanaszkiewicz** [comment]
I personally don't think this is a good way to deal with such stuff. I'd rather have it the way GitHub does in a top-right corner.

**Comment by gvwilson** [comment]
Can you quickly implement your idea and we can compare them on screen?

**Comment by pbanaszkiewicz** [comment]
Here:
screen shot 2015-05-19 at 19 51 09
screen shot 2015-05-19 at 19 51 13

**Comment by gvwilson** [comment]
Sure - please close mine and implement/merge this.

On 2015-05-19 1:52 PM, Piotr Banaszkiewicz wrote:
>
> Here:
> screen shot 2015-05-19 at 19 51 09 
> <https://cloud.githubusercontent.com/assets/72821/7709923/987ceb78-fe60-11e4-8473-34399b5f6c8e.png>
> screen shot 2015-05-19 at 19 51 13 
> <https://cloud.githubusercontent.com/assets/72821/7709924/98ad7d6a-fe60-11e4-8204-0dc9b3b8924c.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/pull/280#issuecomment-103613414>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request closed without merging**
