### PR TITLE
updated email addresses

### PR DESCRIPTION
**Pull request by elizabethwilliams8**
Addresses issue number #1448

### CODE REVIEW

**Comment by maneesha** [comment]
@elizabethwilliams8   Can you include the django migration for this change?  If not I can do it.

**Comment by tracykteal** [comment]
Thanks @maneesha, I don't know how to do that and I'm not sure @elizabethwilliams8 does either. Could you provide guidance?

**Comment by maneesha** [comment]
I ran `makemigrations` and it looks like this is good as is.  I'll leave it to @pbanaszkiewicz  to verify and merge.

**Comment by pbanaszkiewicz** [comment]
Approved the changes for v2.5. Thanks @elizabethwilliams8!

This fixes #1448.

@maneesha: Travis-CI should check migrations as part of testing process, but I've just now discovered it's not working correctly.

**Pull request merged**
