### PR TITLE
Add one-off command line tool to import trainee's progress

### PR DESCRIPTION
**Pull request by chrismedrela**
~~**Not ready to be merged yet.**~~

@gvwilson, have you made any changes? If yes, can you send them, so that I can work on it.

### CODE REVIEW

**Comment by gvwilson** [comment]
Nope, haven't made any changes yet.

**Comment by pbanaszkiewicz** [comment]
We're planning on merging this in v1.7 or not?

**Comment by gvwilson** [comment]
Let's get 1.7 out the door and do this as a patch release - I need to 
test it with the latest data from the spreadsheet.

**Comment by chrismedrela** [comment]
This works. I'll refactor it tomorrow and it'll be ready for review.

@pbanaszkiewicz, should not it be v1.7.1?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela you're right, this should be v1.7.1, sorry.

**Comment by chrismedrela** [comment]
Ready for review.

**Comment by chrismedrela** [comment]
Committed `awarded.json` file.

**Comment by pbanaszkiewicz** [comment]
Well, if it's a one-off command and it works on production data, then I guess it's fine to merge? cc @gvwilson

**Pull request merged**
