### PR TITLE
Allowing search by known airport.

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Add pulldown field for airport IATA code to instructor matching form.
2.  Add logic to process airport *or* latitude+longitude.
3.  Add some error reporting.

### CODE REVIEW

**Comment by wking** [comment]
On Fri, Jan 02, 2015 at 01:51:55PM -0800, Greg Wilson wrote:
> -    persons = None
> +    persons, messages = None, []

When you're setting a bunch of things an immutable constant, I'm fine
with this multiple-assignment.  For example:

  a = b = … = None

However, I think it's not worth the confusion for unrelated
assignments like this.  I think:

  persons = None
  messages = []

reads more clearly, and also makes it easier to follow the history if
the name or default for one variable changes (since changes to the
other variable aren't also churning that line).

> +            valid, lat, long = form.get_lat_long()
> +            if valid:

To get nicer error messages, how about raising errors if the data is
invalid:

  if iata is None:
      if (lat == None) or (long == None):
          raise ValidationError(
              'Cannot specify both an airport code and a latitude or '
              'longitude.  Pick one or the other.')
      return True, lat, long
  if (lat != None) or (long != None):
      raise ValidationError(
          'Must specify either an airport code or a latitude/longitude')
  airport = Airport.objects.get(iata=iata)
  return airport.latitude, airport.longitude

I also prefer 'is' to '==' for comparing with singleton immutables
like None, and the implicit precedence of the language avoid
unnecessary parenthesis.  That gets us:

  if lat is None or long is None:

sometimes I collapse that around the shared constant:

  if None in [lat, long]:

which looks the most readable to me.  Those are just my preferences
though, go with whatever you feel is most readable (and maybe write up
and motivate your choices in the CONTRIBUTING.md style guide?).

Then I'd use the checks in from get_lat_long in InstructorsForm.clean
[1] to avoid the need for a doubled check like:

>      if request.method == 'POST':
>          form = InstructorsForm(request.POST)
>          if form.is_valid():
>  
> +            valid, lat, long = form.get_lat_long()
> +            if valid:

which says “Does is_valid() think we're valid?  Does get_lat_long()
think we're valid?”  It's better to plug into Django's built-in
validation logic than to add another layer in the view code.

[1]: https://docs.djangoproject.com/en/1.7/ref/forms/validation/

**Comment by gvwilson** [comment]
> I think:
>
> persons = None
> messages = []
>
> reads more clearly, and also makes it easier to follow the history if
> the name or default for one variable changes (since changes to the
> other variable aren't also churning that line).

Agreed; updated.
>
> > + valid, lat, long = form.get_lat_long()
> > + if valid:
>
> To get nicer error messages, how about raising errors if the data is
> invalid:
>
> if iata is None:
> if (lat == None) or (long == None):
> raise ValidationError(
> 'Cannot specify both an airport code and a latitude or '
> 'longitude. Pick one or the other.')
> return True, lat, long
> if (lat != None) or (long != None):
> raise ValidationError(
> 'Must specify either an airport code or a latitude/longitude')
> airport = Airport.objects.get(iata=iata)
> return airport.latitude, airport.longitude
>
Agreed - can you do a sweep on all of the code for FIXMEs saying "error 
messages needed" and make error reporting consistent?  (Is there a 
standard way in Django to do this, or does everyone just have a context 
variable called 'error_messages' that they handle themselves?)
> I also prefer 'is' to '==' for comparing with singleton immutables
> like None, and the implicit precedence of the language avoid
> unnecessary parenthesis. That gets us:
>
> if lat is None or long is None:
>
Sure, changed.
> sometimes I collapse that around the shared constant:
>
> if None in [lat, long]:
>
> which looks the most readable to me.

I think that is less readable, so I've gone with the first form.

> Those are just my preferences
> though, go with whatever you feel is most readable (and maybe write up
> and motivate your choices in the CONTRIBUTING.md style guide?).
>
I'll try to get to that..
> Then I'd use the checks in from get_lat_long in InstructorsForm.clean
> [1] to avoid the need for a doubled check like:
>
I didn't follow this one - can you PR my PR with the changes you want?
Thanks, and happy New Year,
Greg

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment]
On Fri, Jan 02, 2015 at 03:09:06PM -0800, Greg Wilson wrote:
> > > + valid, lat, long = form.get_lat_long()
> > > + if valid:
> >
> > To get nicer error messages, how about raising errors if the data is
> > invalid:
> > …
>
> Agreed - can you do a sweep on all of the code for FIXMEs saying
> "error messages needed" and make error reporting consistent?

Is that just:

  $ git grep FIXME origin/pr/117
  … apparently unrelated FIXMEs …
  origin/pr/117:workshops/views.py:            pass # FIXME: error message
  origin/pr/117:workshops/views.py:        title, data = 'Error', None # FIXME - need an error message

> Is there a standard way in Django to do this, or does everyone just
> have a context variable called 'error_messages' that they handle
> themselves?

I'd expect Django to display the errors automatically if you're using
{{ form.as_* }} (e.g. as_p or as_table) in your templates [1].

> > Then I'd use the checks in from get_lat_long in
> > InstructorsForm.clean [1] to avoid the need for a doubled check
> > like:
>
> I didn't follow this one - can you PR my PR with the changes you want?

Sure, I'll likely have time tonight or over the weekend.

[1]: https://docs.djangoproject.com/en/1.7/ref/forms/api/#how-errors-are-displayed

**Comment by gvwilson** [comment]
> > Is there a standard way in Django to do this, or does everyone just
> > have a context variable called 'error_messages' that they handle
> > themselves?
>
> I'd expect Django to display the errors automatically if you're using
> {{ form.as_* }} (e.g. as_p or as_table) in your templates [1].
>
Good enough - is there any guidance on how to display errors in other 
situations consistently?  (I'd like to add to style guidelines when I 
get a chance to write them).

Thanks, and thanks for the fixes,
Greg

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment]
On Sat, Jan 03, 2015 at 05:38:05PM -0800, Greg Wilson wrote: 
> > > Is there a standard way in Django to do this, or does everyone
> > > just have a context variable called 'error_messages' that they
> > > handle themselves?
> >
> > I'd expect Django to display the errors automatically if you're
> > using {{ form.as_* }} (e.g. as_p or as_table) in your templates
> > [1].
>
> Good enough - is there any guidance on how to display errors in
> other situations consistently?  (I'd like to add to style guidelines
> when I get a chance to write them).

The validation docs [1] I linked earlier [2] lay out the validation
process and explain where to hook in if you want to make:

* field-specific checks that could raise field-specific errors or
* multi-field checks that raise general errors or field-specific
  errors.

I'd just read that over, and ask more specific questions if you can't
figure out where to put a particular check you have in mind.

[1]: https://docs.djangoproject.com/en/1.7/ref/forms/validation/
[2]: https://github.com/swcarpentry/amy/pull/117#issuecomment-68570687

**Pull request merged**
