### PR TITLE
Reporting SCF members

### PR DESCRIPTION
**Pull request by gvwilson**
Work in progress: will address #539.

Lots of issues with this, mostly because of things I don't understand in Django:

1.  The call to `get_members` in `ExportMembersView` in `api/views.py` is executed as the class is defined, which means it's run every time *any* view is displayed, which is bad. How can its execution be delayed?
2.  Inside `get_members` in `workshops/util.py`, should use a Django query to find everyone with an instructor badge who has a task of type 'instructor' that is less than two years old.
3.  Should merge to create queryset using Django queries as well.
4.  Need to add tests.

Help with 1-3 would be very welcome.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
First of all, @gvwilson, please do as following:

```shell
$ git checkout develop
$ git fetch
$ git reset --hard upstream/develop
$ git checkout reporting-members
$ git rebase develop
```

(this is assuming that you have `upstream` remote pointing to @swcarpentry/amy)
We want to only have commits you added. Thanks!

**Comment by gvwilson** [comment]
After this:

~~~

$ git checkout develop
$ git fetch
$ git reset --hard upstream/develop
$ git checkout reporting-members
$ git rebase develop
~~~


I resolve the conflicts in `bower.json` and `workshops/__init__.py` 
(version numbers), then get this:

~~~
~/s/amy: git status
rebase in progress; onto 723778c
You are currently rebasing branch 'reporting-members' on '723778c'.
   (all conflicts fixed: run "git rebase --continue")

nothing to commit, working directory clean


~/s/amy: git rebase --continue
Applying: Version bump to v0.6.1
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase 
--abort".
~~~

What's the next step?

**Comment by pbanaszkiewicz** [comment]
@gvwilson skip 'Version bump to v0.6.1'.

**Comment by pbanaszkiewicz** [comment]
@gvwilson after you finish rebasing, do `git push --force` to update your remote branch.

**Comment by gvwilson** [comment]
Durrr?

**Comment by gvwilson** [comment]
Messed up the Git - destroying this and will try again.

**Pull request closed without merging**
