### PR TITLE
workshops/test/test_event.py: Add TestEventViews.test_add_minimal_event

### PR DESCRIPTION
**Pull request by wking**
Only setting the non-blank fields (published, site, and tags).  This
ensures that the form respects our blanks (e.g. they don't need a URL,

### CODE REVIEW

**Comment by gvwilson** [comment]
Looks good to me.

**Comment by wking** [comment]
On Wed, Feb 18, 2015 at 11:13:52AM -0800, Greg Wilson wrote:
> Looks good to me.

Actually, it looks like the form currently struggles with two
successive empty entries, because both will have NULL URLs, and so the
form parser things the second isn't unique (SQLite doesn't mind
though).  We probably want another test checking that case before we
merge this PR.

**Comment by wking** [comment]
On Wed, Feb 18, 2015 at 11:26:10AM -0800, W. Trevor King wrote:
> Actually, it looks like the form currently struggles with two
> successive empty entries, …

Ok, there's another test and a better description in 295dd1e8
(workshops/test/test_event.py: Test adding two minimal Events,
2015-02-18), and a fix following a Django core dev in 2171bc48
(workshops/models.py: Work around '' TextInput default for Event.url,
2015-02-18).  I think this is ready for merging now.  We can go
through, test-for, and fix other instances bumping into Django's 4136
[1] in follow-up PRs.

[1]: https://code.djangoproject.com/ticket/4136

**Comment by wking** [comment]
On Wed, Feb 18, 2015 at 10:31:58PM -0800, W. Trevor King wrote:
> I think this is ready for merging now.

Bump :).  This fixes #190, which is tagged as “essential”.

**Pull request merged**
