### PR TITLE
fixing nav covering content issue #1210

### PR DESCRIPTION
**Pull request by askingalot**
Fix for #1210

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Hello @askingalot. Thank you for your contribution.

Unfortunately there may be a case when we have low resolution, but the top navbar height is correct (60px). With this solution, we'd end up with a blank gap just below the top navbar in such case.

Is it possible to condition `body`'s `padding-top` not only on screen width, but also navbar height, @askingalot?

**Comment by askingalot** [comment]
@pbanaszkiewicz I'll take a look.

**Comment by askingalot** [comment]
@pbanaszkiewicz, I just did a round of testing based on your feedback. I basically mimicked different resolutions with the browser zoom feature, and I used the mobile view in the browser dev tools. I did see a couple of zoom levels that had a blank gap at the top. I think this (at least roughly) reproduces the issue you raised.

I don't know of a way in pure CSS to set the padding of an element based on the height of another. If you know of one, I'd love to hear about it. All I can think to do is implement a solution in javascript. I'll give it a shot.

BTW, I also noticed that the my solution doesn't take the Filter sidebar into consideration, so I can look into pushing it down when the navbar gets bigger too.

**Comment by pbanaszkiewicz** [comment]
Hello @askingalot,

> @pbanaszkiewicz, I just did a round of testing based on your feedback. I basically mimicked different resolutions with the browser zoom feature, and I used the mobile view in the browser dev tools. I did see a couple of zoom levels that had a blank gap at the top. I think this (at least roughly) reproduces the issue you raised.

Exactly.

> I don't know of a way in pure CSS to set the padding of an element based on the height of another. If you know of one, I'd love to hear about it. All I can think to do is implement a solution in javascript. I'll give it a shot.

I don't know anything like that either.

> BTW, I also noticed that the my solution doesn't take the Filter sidebar into consideration, so I can look into pushing it down when the navbar gets bigger too.

I plan to make a general AMY dashboard redesign (something like this: http://coderthemes.com/velonic_3.0/admin_3/), and the biggest changes would be:
1. navigation bar and sidebar switched
2. darker colors for navigation

I hope we'd end up with cleaner look, nicer navigation and easier to maintain templates (e.g. now we have some views fluid and some non-fluid).

For now I'd say we drop this PR if we're unable to fix this issue.

**Comment by askingalot** [comment]
That’s fine. If you’re gonna do a redesign soon, i agree it’s not worth continuing to work on this.

**Pull request closed without merging**
