### PR TITLE
Add tasks from person edit

### LINKED ISSUE #391: Should be able to add a task from the 'Edit Person' page
We can add Awards from the 'Edit Person' page - should also be able to add tasks.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #391.

More in the commit messages.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
I added the tests.

This implementation includes a compromise between UI clearness and usefulness. I'd like someone to decide if it's a change for good or for bad.

**Comment by gvwilson** [comment]
It's a good start - thanks.  A couple of changes:

1.  I'd put the existing awards/tasks *above* the form to add more, not below.
2.  After adding a new award/task, the user should be returned to the same tab, not to the main "Person" tab.

Other than that, :+1:.

**Comment by pbanaszkiewicz** [comment]
Hi Greg,

On Thu, Jul 9, 2015 at 7:23 PM, Greg Wilson <notifications@github.com>
wrote:

> It's a good start - thanks. A couple of changes:
>
>    1. I'd put the existing awards/tasks *above* the form to add more, not
>    below.
>
> I thought about this, and decided a while ago to put form above the
listing.

The reason was that some people (like yourself) have a ton of tasks related
to them, so if admin wanted to add a new task they'd have to scroll down to
the bottom.

Do you still want to shift forms and listings?

>
>    1. After adding a new award/task, the user should be returned to the
>    same tab, not to the main "Person" tab.
>
> It's a downside of using these tabs from Bootstrap, because we cannot
redirect to the specific tab.

The only solution I can think of is to change tabs based on the message
returned from Django messaging framework.

I'll try to work this out.

Cheers,
Piotr

**Comment by pbanaszkiewicz** [comment]
@gvwilson switching tabs works (it won't get any better, I think; unless we switch plugins). Cheers :-)

**Comment by gvwilson** [comment]
Ah, good thinking - yes, leave the form above the tasks.

**Comment by pbanaszkiewicz** [comment]
Do you want to move the award form to the bottom? Pro: there's only a limited number of badges a person can get, so the listing will never be long. Con: inconsistent with the task form placement.

**Comment by gvwilson** [comment]
Please keep it consistent with the task display (form, then listing).

**Pull request merged**
