### PR TITLE
Remove timeline from admin dashboard

### LINKED ISSUE #1135: Remove timeline from dashboard
Is the timeline on the admin dashboard used by anybody?

### PR DESCRIPTION
**Pull request by chrismedrela**
Fixes #1135.

Is the `vis` library used anywhere in AMY?

### CODE REVIEW

**Comment by narayanaditya95** [comment]
>Is the vis library used anywhere in AMY?

I don't think so.

**Comment by chrismedrela** [comment]
So I've removed `vis` library. Please merge if you think it's fine.

**Comment by pbanaszkiewicz** [comment]
Asked Giacomo for feedback on timeline and TODOs. Please hold on with this for now.

**Comment by chrismedrela** [comment]
Merging since we got feedback from @gperu (see #1135).

**Pull request merged**
