### PR TITLE
Suppressing invalid HTTP HOST notifications

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This one:

* stops sending notifications to me (and Greg, as of #595)
* starts sending notifications to our sysadmin mailing list
* stops informing about "invalid HTTP_HOST header" errors (someone requests our pages without proper HOST header, usually "104.130.229.225" [which is server's IP address] or "*.software-carpentry.org")

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
@wking maybe you know a way to force Nginx to only accept requests that come with proper HOST header?

Our Nginx configuration is here:

```nginx
# amy_nginx.conf

upstream django {
    server unix:///home/amy/amy_site/amy.sock;
    #server 127.0.0.1:8001;
}

# configuration of the server
server {
    #listen 80;
    listen 443 ssl;
    server_name amy.software-carpentry.org;

    # ... TLS details

    charset utf-8;

    # max upload size
    client_max_body_size 20M;

    # Django media
    #location /media  {
    #    alias /home/amy/amy_site/amy/media;
    #}

    location /static {
        alias /home/amy/amy_site/amy/static;
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass django;
        include /home/amy/amy_site/uwsgi_params;
    }
}
```

**Comment by pbanaszkiewicz** [comment]
@gvwilson can you please make sure that AMY's mail account is whitelisted on the sysadmin mailing list?

**Comment by gvwilson** [comment]
Sure - what's the account?

**Comment by pbanaszkiewicz** [comment]
It's amy-noreply@software-carpentry.org, thanks.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Greg WilsonSent: Monday, 14 December 2015 17:27To: swcarpentry/amyReply To: swcarpentry/amyCc: Piotr BanaszkiewiczSubject: Re: [amy] Suppressing invalid HTTP HOST notifications (#601)Sure - what's the account?


—Reply to this email directly or view it on GitHub.

**Comment by gvwilson** [comment]
Hm - can't see a way to add an address to a whitelist w/out making it a 
recipient.  Digging...

**Comment by gvwilson** [comment]
Found it (I think). Can you please test?

**Comment by pbanaszkiewicz** [comment]
Okay, test passed. I'll merge soon.

**Pull request merged**
