### PR TITLE
Add default ordering to Event

### LINKED ISSUE #150: Events should be ordered by start date, not by insertion order
The default display of events should sort them by start date (or equivalently slug), not by table insertion order.  (Right now, training cohorts are converted to events after actual events have been added, so all the training cohorts show up out of time order.)

### PR DESCRIPTION
**Pull request by sburns**
Fixes #150.

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 01:14:24PM -0800, Scott Burns wrote:
>   * Add default ordering to Event

Where else do we list events?  Do we want to add order_by() bits there
to avoid useless sorting when we don't need it?  From [1]:

  If you don’t want any ordering to be applied to a query, not even
  the default ordering, call order_by() with no parameters.

[1]: https://docs.djangoproject.com/en/1.7/ref/models/querysets/#django.db.models.query.QuerySet.order_by

**Comment by sburns** [comment]
The admin page?

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 01:55:24PM -0800, Scott Burns wrote:
> The admin page?

We'd want that sorted the same way, I think.  I don't see any
event_set or other calls that use Event queries for calculations
(instead of for displaying the query results to the user), but I
haven't looked all that hard.

**Comment by sburns** [comment]
I went with Meta ordering so future devs get the ordering "for free". If you'd prefer just ordering in the view, let me know.

**Comment by gvwilson** [comment]
Looks good to me.

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 11:48:04PM -0800, Scott Burns wrote:
> I went with Meta ordering so future devs get the ordering "for
> free". If you'd prefer just ordering in the view, let me know.

I like the Meta ordering (clearing ordering where you don't need it is
DRYer than trying to manually setup the same ordering where you do
need it), but when adding Meta ordering I think it's good to check for
any existing calls that don't need newly-default ordering.  I haven't
turned any up (but as I said I didn't look very hard).  If noone else
is interested in looking, I'm fine with merging this as is.  If we
find unorderable calls we missed, we can always fix them later.

**Comment by gvwilson** [comment]
+1.

**Pull request merged**
