### PR TITLE
Making home page lay out more cleanly

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Is this what admins want?

**Comment by gvwilson** [comment]
It's certainly what *I* want - even at high res, my screen can't show 
four columns without items wrapping.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I'm thinking about how to do this better, because with your changes the "recently changed" will become invisible. Maybe http://getbootstrap.com/components/#nav-tabs for Current/Uninvoiced/Unpublished would work?

**Comment by gvwilson** [comment]
Sure - check with Maneesha?

**Comment by maneesha** [comment]
I've only used this on one screen and have had no problems with the layout. I can try on some other monitors and see what this looks like.  

However, I've never used the rightmost column (Recently Changed), so I'd be OK removing that if the screen is too crowded.  Much more valuable would be to see "Created by user on date" and "Last updated by user on date" on each page (see #518)

**Comment by gvwilson** [comment]
Thanks @maneesha - @pbanaszkiewicz, how about we accept this change 
(which moves the event log down on the home page) and then prioritize 
#518 for the next release?

**Comment by pbanaszkiewicz** [comment]
@maneesha @gvwilson in this case I suggest moving the Log out of the dashboard to its own page. I'll submit a PR for that.

In the long run we may have customizable dashboards or dashboard layouts specific to each user group (superadmin, admin, steering committee).

I'll also start working on #518 soon.

**Comment by pbanaszkiewicz** [comment]
Superseded by #535.

**Pull request closed without merging**
