### PR TITLE
Debrief: exclude stalled, TTT and unresponsive events from search

### LINKED ISSUE #643: Remove instructor training from debriefing list

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
Additionally fix indentation in the template (it was tabs, should be
spaces) and speed up the retrieval of related objects (event, person,
role).

This fixes #643.

### CODE REVIEW

**Comment by gvwilson** [comment]
Why exclude TTT?

**Comment by pbanaszkiewicz** [comment]
@rgaiacs: see @gvwilson comment above.

**Comment by rgaiacs** [comment]
> Why exclude TTT?

I thought that people delivering TTT didn't want to get spam from debriefing sessions.

**Comment by gvwilson** [comment]
Undecided - please keep 'em in for now.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I brought TTT events back, will merge soon if you don't have any other objections.

**Comment by gvwilson** [comment]
:+1:

**Pull request merged**
