### PR TITLE
Remove help text of autocomplete fields

### PR DESCRIPTION
**Pull request by chrismedrela**

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
What's rationale behind this removal?

**Comment by chrismedrela** [comment]
After walkthroughs with AMY users, I think that autocomplete fields are intuitive and don't require any explanation. Removing these help texts simplifies UI. The more text on webpages, the more likely it is that an important message is left unread (less is more).

**Comment by gvwilson** [comment]
:+1: - if this is what Chris got from user testing, let's go with it.

**Comment by pbanaszkiewicz** [comment]
This one likely needs to be updated (I think I found 2 more places where `help_text=AUTOCOMPLETE_HELP_TEXT` is used).

**Comment by pbanaszkiewicz** [comment]
@chrismedrela can you please update this PR?

**Comment by chrismedrela** [comment]
@pbanaszkiewicz , done.

**Pull request merged**
