### PR TITLE
New host: self-organized

### LINKED ISSUE #484: Indicate "self-organized" for administrator of self organized workshops
Right now AMY directs you to leave this field blank if self organized.
I'd like to see "self-organized" as one of the drop down options.  Later on, if I'm querying the database directly to find all self-organized workshops I'd rather write `SELECT * FROM events WHERE administrator = 'self-organized'` instead of `SELECT * FROM events WHERE administrator IS NULL`.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #484.

A new host ('self-organized') was added.

Events that had no administrator and one of the following conditions were updated with 'self-organized' as admin:

* have "self-organized" in notes, or
* have "self organized" in notes, or
* have "Not applicable since self-organized" as invoice status

WIP since I'm waiting for the list of self-organized events.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
@maneesha could you provide me with a list of self-organized workshops?

For the record, Tracy said there are no self-organized workshops for DC.

**Comment by maneesha** [comment]
I've gone through everything from Aug. 1, 2015 on.  Any self organized workshop is noted as such in the invoice status.

I can go farther back than August 2015 but that's before I worked here so I'd be digging through old emails for clues.

Note this does not include EU & UK workshops - since I don't track them I don't know their history.

**Comment by pbanaszkiewicz** [comment]
@maneesha ok, sure. Then my migration is enough. I'll ask Giacomo and see if he can add some workshops and then un-mark the "WIP" label for Greg. Thanks!

**Comment by pbanaszkiewicz** [comment]
We're not waiting for Giacomo, he'll send that later. @gvwilson I think this is ready for review.

**Comment by pbanaszkiewicz** [comment]
@gvwilson could you please review this PR? Thanks.

**Pull request merged**
