### PR TITLE
Find instructors by country + other improvements

### LINKED ISSUE #394: Allow search for instructors by country
The "Locate Instructors" form should allow selection of a country, and should return a list of all instructors whose nearest airport is in that country.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
The Find Instructors page had a facelifting.

This fixes #394.

All changes are listed in the commit messages, the important and visible ones:

1. No more "wanted" field; instead pagination with sorting by distance is in place.
2. Filter instructors by their country.

### CODE REVIEW

**Comment by gvwilson** [comment]
1.  After clicking "More... Find Instructors", the page shows *all* instructors (because there's no filtering in place).  This isn't the behavior I expect - it should initially be blank.
2.  There are some layout problems: the search boxes on the left underlie the display of instructors.

screen shot 2015-07-09 at 1 08 23 pm

**Comment by pbanaszkiewicz** [comment]
Hi Greg,

On Thu, Jul 9, 2015 at 7:18 PM, Greg Wilson <notifications@github.com>
wrote:

>
>    1. After clicking "More... Find Instructors", the page shows *all*
>    instructors (because there's no filtering in place). This isn't the
>    behavior I expect - it should initially be blank.
>
>
Maybe you expect this behavior because it's what you're used to?

I will argue for the new behavior:
1. it's consistent with other pages with filters
2. it drops one barrier for admins (specifying number of wanted instructors)


>
>    1. There are some layout problems: the search boxes on the left
>    underlie the display of instructors.
>
>
Confirmed (it appears on the lower resolution displays), and I have a fix
for that ready.

**Comment by gvwilson** [comment]
On 2015-07-09 1:33 PM, Piotr Banaszkiewicz wrote:
> >
> > 1. After clicking "More... Find Instructors", the page shows *all*
> > instructors (because there's no filtering in place). This isn't the
> > behavior I expect - it should initially be blank.
> >
> >
> Maybe you expect this behavior because it's what you're used to?
>
Yes, probably.

> I will argue for the new behavior:
> 1. it's consistent with other pages with filters
> 2. it drops one barrier for admins (specifying number of wanted 
> instructors)
>
I'm not arguing about the paginated display - I like that.  I'm arguing 
that being shown *all* instructors, in alphabetical order, is... 
overwhelming...  @amyrbrown ?

**Comment by pbanaszkiewicz** [comment]
On Thu, Jul 9, 2015 at 7:38 PM, Greg Wilson <notifications@github.com>
wrote:

> On 2015-07-09 1:33 PM, Piotr Banaszkiewicz wrote:
> > >
> > > 1. After clicking "More... Find Instructors", the page shows *all*
> > > instructors (because there's no filtering in place). This isn't the
> > > behavior I expect - it should initially be blank.
> > >
> > >
> > Maybe you expect this behavior because it's what you're used to?
> >
> Yes, probably.
>
> > I will argue for the new behavior:
> > 1. it's consistent with other pages with filters
> > 2. it drops one barrier for admins (specifying number of wanted
> > instructors)
> >
> I'm not arguing about the paginated display - I like that. I'm arguing
> that being shown *all* instructors, in alphabetical order, is...
> overwhelming... @amyrbrown ?


So when you go to Ebay, you expect to see no items for sale unless you add
some filtering? :-)

**Comment by gvwilson** [comment]
Good point.

**Comment by amyrbrown** [comment]
Belatedly, I agree that all instructors should be listed until there is a filter is specified. An alphabetized list of all instructors is not very useful, but it's (a) logical, and (b) no less useful than a blank page.

**Comment by gvwilson** [comment]
Make it so.

**Comment by pbanaszkiewicz** [comment]
Okay, so it's all resolved now. Merging.

**Pull request merged**
