### PR TITLE
Make update from requirements

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
There's something weird in these commits. I think you might have merged master into develop and then added new commit.

Please do the following:
```
git checkout develop
git pull upstream develop
git checkout make-update-from-requirements
git rebase develop
git push --force
```

**Comment by gvwilson** [comment]
I don't have a branch called 'develop', either on my laptop or in 
GitHub. ???

On 2015-08-30 7:39 PM, Piotr Banaszkiewicz wrote:
>
> There's something weird in these commits. I think you might have 
> merged master into develop and then added new commit.
>
> Please do the following:
>
> |git checkout develop git pull upstream develop git checkout 
> make-update-from-requirements git rebase develop git push --force |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/pull/478#issuecomment-136174189>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
Okay, so you can do something like this:
```
git branch -D develop # make sure there's no such branch
git fetch upstream develop  # fetch the branch's head
git checkout -b develop upstream/develop  # make new branch of off the head
git checkout make-update-from-requirements  # go back
git rebase develop  # rebase
git push --force  # push the rebased code
```

**Comment by pbanaszkiewicz** [comment]
Or you can recreate the whole repository, but I wouldn't do that if I had some other branches.

**Pull request closed without merging**
