### PR TITLE
Add bulk person ingest from CSV

### LINKED ISSUE #27: Add form for bulk addition of new persons
The app should allow admins to upload a CSV file containing names, email addresses, and optionally roles as well.  The uploaded data should be validated and displayed for further editing before being added.

* If roles are not included in the data, everyone should be marked as a learner, but a warning should be raised.
* If roles are specified, an event must also be specified, and a task should be created for each person showing what role they had in that event.
* Instead of using a fixed column ordering, the upload form should allow users to specify which columns contain which fields on the fly.

### PR DESCRIPTION
**Pull request by cudevmaxwell**
Fixes #27. 

Still requires testing and vetting.

### CODE REVIEW

**Comment by cudevmaxwell** [comment]
The most recent pull request from @gvwilson has now been incorporated. There is no longer a validation step, so the copy to a temp file was no longer necessary and was removed. 

If we would like store the bulk add file in the DB as discussed above, I can work on that. 

If not, I can add some tests for the PR as it stands now.

**Comment by gvwilson** [comment]
Hi Kevin,

1. Storing the file data would be useful, but can wait until:

2. The uploaded data is actually stored in the database - when I tested 
this manually, the people from the uploaded CSV weren't added to the DB 
despite `Person` instances being created.  Is some kind of explicit 
commit required?  And should we wrap all of this in a transaction so 
that all the people are added, or none?

Thanks,
Greg

**Comment by wking** [comment]
On Fri, Jan 02, 2015 at 04:23:50PM -0800, Greg Wilson wrote:
> 2. The uploaded data is actually stored in the database - when I
> tested this manually, the people from the uploaded CSV weren't added
> to the DB despite `Person` instances being created.

I see some:

  +            if save:

blocks, but nowhere that defines the ‘save’ variable.

> Is some kind of explicit commit required?  And should we wrap all of
> this in a transaction so that all the people are added, or none?

We don't expect this to be a particularly high-traffic site, so I'd
recommend just turning on ATOMIC_REQUESTS [1].

The Git history for this change is also getting a bit complicated:

  $ git log --graph --topo-order --oneline --decorate origin/master..origin/pr/106
  *   4370df9 (origin/pr/106, cudevmaxwell/27-csv-bulk-add-people) Merge branch 'gvwilson-27-csv-bulk-add-people' into 27-csv-bulk-add-people
  |\  
  | *   3bf43e5 Merged pull request #2
  | |\  
  |/ /  
  | * 7f7d9b6 (gvwilson/27-csv-bulk-add-people) Slimming down
  | * e09f1b2 Merging from master
  | * de8c6a8 Merge branch 'master' into 27-csv-bulk-add-people
  * | 8cbff4d Fixed typo
  * | a61640e Merge changes from master branch.
  * | 1ee7d87 Functional bulk upload from CSV, with user confirmation step.
  * |   7553388 Merge branch 'gvwilson-27-csv-bulk-add-people' into 27-csv-bulk-add-people
  |\ \  
  | * \   37aeabc Merge branch '27-csv-bulk-add-people' of https://github.com/gvwilson/amy into gvwilson-27-csv-bulk-add-people
  | |\ \  
  |/ / /  
  | | _   
  | * 09ec37a Slimming down the fields used to upload tasks after workshops.
  | * 4c41314 Merge branch '27-csv-bulk-add-people' of github.com:cudevmaxwell/amy into 27-csv-bulk-add-people
  * | 98bce91 Merge remote-tracking branch 'upstream/master' into 27-csv-bulk-add-people
  |/  
  * b05d4bd First pass, not processed yet.

so I'd recommend a rebase to consolidate this addition into something
more semantic.  Future devs won't need to know that we made and fixed
a typo, or that there were multiple revisions to adapt to changes on
master, they'll just want to know why the lines we're landing are
needed for bulk-person addition, with a commit message explaining any
tricky bits.

It looks like there are also some merge markers that were commited to
the current branch, instead of resolved during the merge that
introduced them:
 
  +<<<<<<< HEAD
  +=======
  +
  +>>>>>>> 7f7d9b6131850856d29c2448441861740336d8d8

it looks like that particular change landed with 3bf43e5e5 (Merged
pull request #2, 2015-01-02).

[1]: https://docs.djangoproject.com/en/1.7/topics/db/transactions/#tying-transactions-to-http-requests

**Comment by cudevmaxwell** [comment]
I removed the `if save`, sorry I didn't catch it. 

Don't worry, I'll squash this if we decide to merge it. 

Using the latest code in the PR, people added through the bulk ingest are added to People, just on the last page. 

image

You can also tell that they're added because the unique email constraint kicks up a fuss on reupload of  the same csv.

image

**Comment by cudevmaxwell** [comment]
As for the merge artifact, I don't see it in the current HEAD. https://github.com/swcarpentry/amy/pull/106/files

**Comment by wking** [comment]
On Fri, Jan 02, 2015 at 04:52:46PM -0800, Kevin Bowrin wrote:
> As for the merge artifact, I don't see it in the current
> HEAD.

It looks like you pushed 7014da8 (Removed merge artifact), ec5ed8a
(Updated to no longer copy uploaded file to temp location), and
0d3d91a (Removed reference to old parameter) after my comment.

Looking at:

  $ git diff origin/master..0d3d91a

I also see some trailing whitespace coming in.  It's obviously a minor
issue, but we might as well clean it up while we're polishing this PR.

**Comment by gvwilson** [comment]
Superseded by #131 - thanks again for getting this rolling.

**Pull request closed without merging**
