### PR TITLE
Airport details page: fix wrong URL param causing 500

### LINKED ISSUE #1008: Airport code >> server error in profile update form view
When you click on the link with the three character airport code in the view to accept a profile update request, it takes you to a 500 Server error.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #1008.

The error was: template used
`{% url 'airport_details' iata=airport.iata %}`
instead of
`{% url 'airport_details' airport_iata=airport.iata %}`
which caused 500 on every airport details page.

### CODE REVIEW

**Comment by gvwilson** [comment]
:+1: Can you do a quick deploy this week to get this to @maneesha and others?

**Comment by pbanaszkiewicz** [comment]
This week? Like before midnight today? Nope. :-)

However, Monday (tomorrow) definitely.

**Comment by gvwilson** [comment]
Sure, and thank you.

**Comment by narayanaditya95** [comment]
Fixes #1012

**Pull request merged**
