### PR TITLE
Adding the Amy logo to the login page

### PR DESCRIPTION
**Pull request by gvwilson**
This should probably be done using an 'include' directive of some kind, since it's exactly the same HTML as is used in index.html.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
> This should probably be done using an 'include' directive of some kind, since it's exactly the same HTML as is used in index.html.

Yes, can you please add `amy-logo.html` template with `<table>…</table>`, and then replace it in both `index.html` and `login.html` with inclusion tag: `{% include 'amy-logo.html' %}`?

**Comment by gvwilson** [comment]
Sure - where does amy-logo.html go in order for both 
workshops/templates/workshops and workshops/templates/accounts to find it?
G

On 2015-04-29 2:16 AM, Piotr Banaszkiewicz wrote:
>
>     This should probably be done using an 'include' directive of some
>     kind, since it's exactly the same HTML as is used in index.html.
>
> Yes, can you please add |amy-logo.html| template with 
> |<table>…</table>|, and then replace it in both |index.html| and 
> |login.html| with inclusion tag: |{% include 'amy-logo.html' %}|?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/pull/250#issuecomment-97319083>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
Hi,

if you put the template into `workshops/templates/amy-logo.html`, it will work.

The inclusion tag should address `amy-logo.html`, ie. for both `index.html` and `login.html`: `{% include "amy-logo.html" %}`.

Remember to put `{% load static %}` on top of `amy-logo.html`.

Cheers

**Comment by pbanaszkiewicz** [comment]
Sorry, I did notice you updated this PR. It looks good.

**Pull request merged**
