### PR TITLE
Timeline feature

### LINKED ISSUE #570: Add timeline feature
When #537 gets implemented we'll be able to render admin-specific dashboard for our dear admins.

@maneesha suggested adding a timeline to event TODOs (#561), maybe displayed on the dashboard.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
The timeline is displayed on top of the dashboard.  It allows for zooming and dragging (needs to be highlighted with a click first).

This fixes #570.

### CODE REVIEW

**Comment by gvwilson** [comment]
I don't know enough to review this code :-(

**Comment by pbanaszkiewicz** [comment]
@gvwilson Can you beta-test it? Download, run, add some TODOs to events (you have to be assigned to them), and see if you like it?

**Comment by gvwilson** [comment]
Probably not 'til after Christmas...

**Comment by maneesha** [comment]
Did I misunderstand what the timeline was going to do?  What I thought was that it would give me a dashboard view of all my upcoming tasks.  I just added in a few to-dos for this week & next but I don't see anything on my timeline.  It's just a blank timeline that I can scroll through - I don't see any function to it.  Let me know if there is another way I should be using it.

**Comment by pbanaszkiewicz** [comment]
@maneesha check if you're assigned to the event that you put the todos at.

**Comment by maneesha** [comment]
Yes -- for example
https://amy.software-carpentry.org/workshops/event/2016-01-06-UNL
https://amy.software-carpentry.org/workshops/event/2016-01-14-uwmadison
https://amy.software-carpentry.org/workshops/event/2016-02-22-tulane

are all  assigned to me and have to-dos this week & next but nothing shows up on my dashboard.

**Comment by pbanaszkiewicz** [comment]
@maneesha can you please visit https://amy.software-carpentry.org/api/v1/todos/user/ and tell me if you get an empty list `[]` or some meaningful data like:

```json
[
    {
        "content": "<a href=\"…",
        "start": "2016-01-11"
    },
    {
        "content": "<a href=\"…",
        "start": "2016-01-18"
    }
]
```

**Comment by pbanaszkiewicz** [comment]
@maneesha just to be sure, please try hard refreshing the website (ctrl+shift+r on Firefox/Linux, probably something else on Mac).

I tried locally reassigning one of the events to me and the timeline works just fine.

**Comment by maneesha** [comment]
A hard refresh doesn't seem to help.  I've tried Chome & Firefox, on Ubuntu
& Windows.. even on a computer I've never used AMY on.

Following your link, I do get a list of dicts:


HTTP 200 OKContent-Type: application/jsonAllow: GET, HEAD, OPTIONSVary: Accept
[
    {
        "content": "<a
href=\"/workshops/event/2015-07-30-ASPB\">2015-07-30-ASPB</a><br><small>Add
helpers from workshop</small>",
        "start": null
    },
    {
        "content": "<a
href=\"/workshops/event/2015-08-24-isu\">2015-08-24-isu</a><br><small>Need
to add helpers</small>",
        "start": null
    },
    {
        "content": "<a
href=\"/workshops/event/2016-02-22-upenn\">2016-02-22-upenn</a><br><small>Confirm
dates (tentative  Monday, February 22nd, and Tuesday, February 23rd
)</small>",
        "start": "2015-11-19"
    },
    {
        "content": "<a
href=\"/workshops/event/2015-08-19-ou\">2015-08-19-ou</a><br><small>Add
learner list - see email from Jonah</small>",
        "start": "2015-12-21"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-02-22-tulane\">2016-02-22-tulane</a><br><small>Make
registration page</small>",
        "start": "2016-01-07"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-02-22-tulane\">2016-02-22-tulane</a><br><small>Add
to surveys & make view page</small>",
        "start": "2016-01-11"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-01-14-uwmadison\">2016-01-14-uwmadison</a><br><small>Send
\"Are you ready\" email</small>",
        "start": "2016-01-11"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-01-06-UNL\">2016-01-06-UNL</a><br><small>send
\"How'd it go\" email </small>",
        "start": "2016-01-11"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-01-06-UNL\">2016-01-06-UNL</a><br><small>Record
attendance in AMY</small>",
        "start": "2016-01-18"
    },
    {
        "content": "<a
href=\"/workshops/event/2016-02-22-tulane\">2016-02-22-tulane</a><br><small>Send
\"Are you ready\" email</small>",
        "start": "2016-02-18"
    }]

**Comment by pbanaszkiewicz** [comment]
@maneesha found the error. It's the missing 'start' value in two of your Todos that's breaking the Javascript.

**Comment by maneesha** [comment]
Got it - I removed those null dates and now things work.
Can we have null dates display an error rather than failing silently?

**Comment by pbanaszkiewicz** [comment]
@maneesha for now I'll fix that issue by removing entries without due date from timeline.

The empty `due` and `additional` are by design - if admins decide they don't want to allow for empty `due` then we'll have it forced to non-empty by v1.4.

**Comment by pbanaszkiewicz** [comment]
@maneesha the new version is on the server. Enjoy!

**Pull request merged**
