### PR TITLE
Display person's username

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
Username was missing on person details page.  This commit adds it on top
of the table with details.

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks - it'll be editable automatically?

**Comment by pbanaszkiewicz** [comment]
It is editable, but it's not in the same place as on the details page. Should I move it to the top?

**Comment by gvwilson** [comment]
I think everything else is consistently ordered, so yes please.

On 2015-06-19 10:49 AM, Piotr Banaszkiewicz wrote:
>
> It is editable, but it's not in the same place as on the details page. 
> Should I move it to the top?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/pull/378#issuecomment-113536239>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
Done.

**Pull request merged**
