### PR TITLE
Add library carpentry links to confirmation pages

### LINKED ISSUE #1401: Add library carpentry links to confirmation pages
Library Carpentry should appear in the link list on the confirmation pages for the instructor training and workshop request forms.

### PR DESCRIPTION
**Pull request by dheles**
Fixes #1401

### CODE REVIEW

**Comment by maneesha** [comment]
Do not merge - this may not be the correct URL.

**Comment by pbanaszkiewicz** [comment]
@maneesha I made you a reviewer, please decide if you give this PR a green light via GitHub review interface.

**Comment by maneesha** [comment]
@libcce and @ErinBecker   can you verify the correct URL for Library Carpentry's website?  Earlier today Erin told me www.librarycarpentry.org is not correct.

**Comment by libcce** [comment]
@maneesha @ErinBecker the URL is https://librarycarpentry.org/

**Comment by maneesha** [comment]
Yes, verifying this is the correct url:  https://librarycarpentry.org/

**Pull request merged**
