### PR TITLE
Bulk-upload: no-op when user and task exist

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
Do nothing if we try to upload user and assigned task that already exist.

This solves #211.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
I went ahead with @wking suggestion (https://github.com/swcarpentry/amy/issues/211#issuecomment-77415417): no UI changes to indicate a specific user ↔ task exist.

**Comment by wking** [comment]
On Wed, Mar 11, 2015 at 11:39:26AM -0700, Piotr Banaszkiewicz wrote:
> Do nothing if we try to upload user and assigned task that already exist.

Looks good to me.

**Comment by pbanaszkiewicz** [comment]
Additionally, a fix for #231 was included here.

**Comment by pbanaszkiewicz** [comment]
Based on the feedback from @wking, I'm merging this one.

**Pull request merged**
