### PR TITLE
Autocompletion with django-selectable

### LINKED ISSUE #233: Autocomplete form fields
Would Amy benefit from installing ajax autocomplete for specific form fields - for example, when selecting a user for a new task.

https://pypi.python.org/pypi/django-ajax-selects
https://github.com/crucialfelix/django-ajax-selects/

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This is work by @shapiromatron with fixes by me.

Original PR: #248.
Resolves #233.

@shapiromatron work was rebased against latest master, all conflicts resolved.

Features:
* autocompletion for events, persons, tasks, sites
* all autocompletion fields use "combobox" widget (not default) - makes it easier to peep into existing values
* old combobox removed

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Big thanks to @shapiromatron for almost all the work. I'm pretty sure I would not get this far with autocompletion myself if not your code :)

**Comment by shapiromatron** [comment]
@pbanaszkiewicz Thanks for taking this one over for me; sorry I was able to finish off myself!

**Comment by pbanaszkiewicz** [comment]
@shapiromatron no problem, as I said — thanks to you it was easy to carry to the end.

If you have some spare time we could always use a hand — there's plenty [to do](https://github.com/swcarpentry/amy/milestones/v0.3).

**Comment by pbanaszkiewicz** [comment]
@wking can you review these changes? Thanks

**Comment by pbanaszkiewicz** [comment]
Rebased against latest master.

@wking, could you give me a green light?

**Comment by wking** [comment]
On Mon, May 25, 2015 at 01:53:04AM -0700, Piotr Banaszkiewicz wrote:
> @wking, could you give me a green light?

Sorry for the delay.  I just dropped a lot of re-roll suggestions into
the current series of commits leading up to 8ec7265.  I can try to
chip on the reroll where the change is just converting A→B→C to A→C',
but for some of the changes I don't understand the motivation
(e.g. shifting the template load calls around).

**Comment by wking** [comment]
The thrust of this PR looks good to me though, so I doubt we'll have
any architectural disagreements to sort out.

**Comment by pbanaszkiewicz** [comment]
Thanks, @wking.

Do you perhaps have a suggestion for me on how to squash two non-consecutive commits? I've seen you suggest a couple times such solution.

**Comment by wking** [comment]
On Mon, May 25, 2015 at 11:16:26AM -0700, Piotr Banaszkiewicz wrote:
> Do you perhaps have a suggestion for me on how to squash two
> non-consecutive commits? I've seen you suggest a couple times such
> solution.

Sure.  I posted something like this in response to [1], but GitHub
seems to have eaten that email ;).

Anyhow squashing any two commits in your branch is straightforward
with ‘git rebase -i …’ as described here [2].  And splitting a commit
into pieces (e.g. when one hunk needs to get squashed into the earlier
commit A, and the rest needs to stay as a separate commit) is
described here [3].

[1]: https://github.com/pbanaszkiewicz/amy/commit/90202d3ad10bf5bdc4a5eb7de3f70c436c44e69e#commitcomment-11352656
[2]: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages
[3]: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Splitting-a-Commit

**Comment by pbanaszkiewicz** [comment]
Hi @wking,

it was a very long rebase for me (took over 5 hours). Can you take a look? I might have missed something…

Cheers,
Piotr

**Comment by pbanaszkiewicz** [comment]
Thanks @wking for the review. I'll fix the issues and then merge.

**Comment by wking** [comment]
On Wed, May 27, 2015 at 10:36:40PM -0700, Piotr Banaszkiewicz wrote:
> Thanks @wking for the review. I'll fix the issues and then merge.

Give me a bit more time, I haven't made it through your reroll yet ;).
It's looking a lot better though :).

**Comment by pbanaszkiewicz** [comment]
@wking ah! Okay, good that I didn't start working on improvements. Thanks!

**Comment by pbanaszkiewicz** [comment]
@wking sorry for pinging you over and over again, but the deadline is coming and some of other features depend on this PR. Could you review it?

**Comment by wking** [comment]
On Sat, May 30, 2015 at 11:48:02PM -0700, Piotr Banaszkiewicz wrote:
> @wking sorry for pinging you over and over again, but the deadline
> is coming and some of other features depend on this PR. Could you
> review it?

Sorry to hold you up :/.  I've looked through the branch leading up to
8e6566b4 (Fix broken tests due to autocomplete, 2015-05-19) and left
comments on the individual commit messages.  This round was a lot
easier to review than the first pass, now that a lot of the churn has
been squashed away.  The commits are also a lot more atomic, so it's
easier to understand the motivation behind the changes.

Anyhow, feel free to stop polishing and just merge this if you don't
have time to go over it again.  I think reviewing and polishing these
PRs to make sure we understand why/how we're changing things is
useful, but I don't expect everyone to agree with me there, or feel as
strongly about it as I do even if they do agree with me ;).

**Comment by pbanaszkiewicz** [comment]
@wking thanks a lot for the review!

> Anyhow, feel free to stop polishing and just merge this if you don't have time to go over it again

I'll polish up and then merge, and then polish up some outstanding PRs.

> I think reviewing and polishing these PRs to make sure we understand why/how we're changing things is useful, but I don't expect everyone to agree with me there, or feel as strongly about it as I do even if they do agree with me ;).

You're right virtually all the time, and I find your feedback well thought and right. I definitely want to "stream" big code changes through you.

Thanks again!

**Comment by pbanaszkiewicz** [comment]
Now I'll rebase against master and then merge.

**Comment by pbanaszkiewicz** [comment]
For some reason this is makred as errored-out in travis-ci, but when I run tests locally (before merging) everything was fine.

**Pull request merged**
