### PR TITLE
Renaming problems report prior to adding another

### PR DESCRIPTION
**Pull request by gvwilson**
Changing the name 'problems' to 'workshops_with_problems' so that we can add an 'instructors_with_problems' report as well.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
`instructors_with_problems` sounds really bad, at least in Polish.

**Comment by gvwilson** [comment]
:-) Suggest alternate wording?  It should be consistent with the 
workshops_with_problems naming.

**Comment by pbanaszkiewicz** [comment]
@gvwilson "Problems amongst instructors"?

**Comment by pbanaszkiewicz** [comment]
This PR was superseded by #530.

**Pull request closed without merging**
