### PR TITLE
Pin D3.js dependency to v3.

### LINKED ISSUE #1010: Graphs not appearing
Go to https://amy.software-carpentry.org/workshops/reports/workshops_over_time/ - the graph of workshops over time has disappeared. Same for other views that used to show graphs.

### PR DESCRIPTION
**Pull request by narayanaditya95**
Fixes #1010

Do we wish to update our code to D3.js v4?

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
I'd go with metrics graphics ~2.10 and D3 ~4.x.x

**Comment by narayanaditya95** [comment]
Why are we interested in downgrading metric graphics?

**Comment by gvwilson** [comment]
None of the graphics appear right now.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz , I've fixed that. https://github.com/swcarpentry/amy/pull/1022

**Pull request closed without merging**
