### PR TITLE
Fix: Turn off HTML autoescape at all revision pages.

### LINKED ISSUE #742: Escaped tags in every revision page
screenshot from 2016-04-02 21 38 15

### PR DESCRIPTION
**Pull request by narayanaditya95**
This fixes #742.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Thanks, I'll take a look during the weekend.

**Comment by pbanaszkiewicz** [comment]
There's a better way: you can `mark_safe` the `semantic_diff` templatetag output like I did with `urlize_newtab`.

@narayanaditya95 can you change the templatetag and ping me back? Thanks!

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz This definitely is the right way of addressing the problem. Thanks for the guidance.

I have changed the templatetag as described. Is it fine?

**Comment by pbanaszkiewicz** [comment]
Definitely! Thanks for your work, it's very appreciated.

**Pull request merged**
