### PR TITLE
Templates: add "Add new *" buttons

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
These buttons are now placed above and below data tables in index pages:

* airports
* events
* persons
* sites
* tasks

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Ref #170.

**Comment by pbanaszkiewicz** [comment]
Preview:
screen shot 2015-03-08 at 23 29 09

**Comment by wking** [comment]
In all_sites.html you have ‘task’ wording which should be ‘site’
wording.  Likely a copy/paste error.  Other than that, this looks good
to me.

**Comment by pbanaszkiewicz** [comment]
@wking thanks! Fixed.

**Comment by wking** [comment]
On Sun, Mar 08, 2015 at 04:26:40PM -0700, Piotr Banaszkiewicz wrote:
> @wking thanks! Fixed.

Good stuff.  This looks ready for merging to me.

**Pull request merged**
