### PR TITLE
Script to show location of airports for addition to database

### PR DESCRIPTION
**Pull request by gvwilson**
Adding all airports (#271) is impractical without a better database, so this script allows easy lookup of airports when/as they need to be added.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Why do you think it's impractical?

**Comment by gvwilson** [comment]
The data we have would take a lot of work to tidy up.  For example, I've already fixed up countries listed as "UK", "United Kingdom", and "England" to all be "United-Kingdom", and "US" and "USA" to be "United-States"; I'm sure there will be more of those before we can start to think sensibly about translating country names to refs to the country table, and then we have to sort out airport naming vs. city naming, etc.  With over 9000 entries, I'm figuring 9 hours of work (?).

**Comment by pbanaszkiewicz** [comment]
Do you think we should rework the way we handle airports to use this list only?

**Comment by gvwilson** [comment]
I think every DB ref to an airport is already a foreign key reference to the `Airport` table, no?

**Comment by pbanaszkiewicz** [comment]
@gvwilson what do you say if we migrate to [`django-airports`](https://github.com/bashu/django-airports)? Similarily as we migrate to `django-countries` in #62.

@wking any thoughts?

**Comment by gvwilson** [comment]
If they have better data than ours, sure.

**Comment by wking** [comment]
On Thu, May 21, 2015 at 10:39:11PM -0700, Piotr Banaszkiewicz wrote:
> @gvwilson what do you say if we migrate to django-airports?
> Similarily as we migrate to `django-countries` in #62.

That looks like a solid package, code-wise.  It's a bit young (just a
few months old), but it has a few forks and a number of folks who've
starred it.  I'd be happier if there were more contributors or issue
activity, but a bunch of stars and few issues isn't a bad combination
;).  So I wouldn't make a serious bet on its long-term stability, but
I think it's safe enough for our use-case.

And the more functionality we can offload to stable, generic, external
packages, the easier it will be to maintain the Amy-specific code, so
+1 from me to migrate.

**Comment by gvwilson** [comment]
OK, go for it.

**Comment by pbanaszkiewicz** [comment]
What I'm a little worried is that django-airport requires spatial-enabled database, and it's a little bit tricky to set up in case of SQLite.

I need some time to think about this issue. It's likely that django-airports can be used only after we completely migrate Amy to Rackspace.

**Comment by wking** [comment]
On Wed, May 27, 2015 at 11:11:43AM -0700, Piotr Banaszkiewicz wrote:
> What I'm a little worried is that django-airport requires
> spatial-enabled database, and it's a little bit tricky to set up in
> case of SQLite.

Are you having problems with SpatiaLite [1,2]?

[1]: https://www.gaia-gis.it/fossil/libspatialite/index
[2]: https://docs.djangoproject.com/en/dev/ref/contrib/gis/db-api/#module-django.contrib.gis.db.backends

**Comment by pbanaszkiewicz** [comment]
I didn't have problems installing in on my own machine but:

1. I use Ubuntu (spatialite comes in as a package), and some devs certainly use Macs
2. I checked briefly for spatialite and it's not installed on our current VPS. From @drio's experience with Small Orange: they'd request money for installing spatialite or deny installing it at all.

**Comment by gvwilson** [comment]
Last time I tried to install SpatiaLite on my Mac it took a while - 
making that a must-have for people doing dev worries me a little. Let's 
defer this one until more pressing things are fixed up?

**Comment by pbanaszkiewicz** [comment]
So the resolution is:

1. don't switch to django-airports
2. don't use the script proposed by @gvwilson in this PR

am I correct?

**Comment by gvwilson** [comment]
Yes to both - we'll add airports manually for now, then come back after 
0.4 and have another look.

**Comment by wking** [comment]
On Wed, May 27, 2015 at 10:17:55PM -0700, Piotr Banaszkiewicz wrote:
> I didn't have problems installing in on my own machine but:
> 
> 1. I use Ubuntu (spatialite comes in as a package), and some devs
> certainly use Macs

Docker FTW ;).  I don't think requiring Docker is too high a bar,
especially with our limited dev pool.

> 2. I checked briefly for spatialite and it's not installed on our
> current VPS. From @drio's experience with Small Orange: they'd
> request money for installing spatialite or deny installing it at
> all.

I'm fine punting on this until we move to a more serious hosting
company :p.

**Comment by pbanaszkiewicz** [comment]
@wking:
> Docker FTW ;)

Good point. Especially now as they added more tools to the set. I can even see [an easy way to set up Docker on OS X](https://docs.docker.com/kitematic/).

> I'm fine punting on this until we move to a more serious hosting company :p.

I've actually migrated to Rackspace, but apparently no-one wants to update the DNS records…

**Comment by gvwilson** [comment]
I'll ask Jon P. to update DNS next week - just want to be on the ground 
in Toronto with him in case anything goes sour.

**Comment by pbanaszkiewicz** [comment]
I talked with an admin and he suggested this workflow:

1. Change TTL of the domain record (`amy.software-carpentry.org`) to something small, like 60
2. Wait 1 day
3. Change the record
4. Wait 1 day to see if everything's okay (if it's not you can quickly rollback thanks to the small TTL )
5. Change the TTL back to previous value

**Comment by wking** [comment]
On Thu, May 28, 2015 at 10:40:13PM -0700, Piotr Banaszkiewicz wrote:
> I talked with an admin and he suggested this workflow…

Sounds good to me.  And the current pool of users is small enough that
in the unlikely event of a catastrophic DNS mixup, you can have folks
add /etc/hosts entries (or their equivalent on other OSes) to resolve
amy.software-carpentry.org while the DNS gets straigtened out.

**Comment by gvwilson** [comment]
This weekend would be a good time to make the change (Amy-the-person 
isn't going to dig in until Monday).  If you're able to do it then, 
please mail her, Giacomo, Aleksandra, and Jon P to confirm.

**Comment by wking** [comment]
On Fri, May 29, 2015 at 03:24:54AM -0700, Greg Wilson wrote:
> Amy-the-person isn't going to dig in until Monday.

This is the main reason I prefer the lowercase ‘amy’ for both the
project and the resulting code ;).

**Comment by gvwilson** [comment]
You reverse engineer a meaning such that 'amy' is an acronym, I'll 
switch to lower case :-)

**Comment by wking** [comment]
On Fri, May 29, 2015 at 11:21:07AM -0700, Greg Wilson wrote:
> You reverse engineer a meaning such that 'amy' is an acronym, I'll
> switch to lower case :-)

If it was an acronym I'd be suggesting uppercase ;).

**Comment by pbanaszkiewicz** [comment]
'AMY' - AdMinister Yourself?

**Comment by gvwilson** [comment]
I like it.

**Pull request closed without merging**
