### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by gvwilson**
This PR starts to build a more comprehensive test framework for Amy.  Please don't bother reviewing until more work has been done on utilities.

### CODE REVIEW

**Comment by gvwilson** [comment]
Finally got this working - @sburns @pbanaszkiewicz @wking can you have a look?

**Comment by wking** [comment]
The basic thrust looks good to me.  A few suggestions:

* You have:

    Person.GENDER_CHOICES_DICT.get(person.gender, None)),

  which should probably be:

    Person.get_gender_display()

  See [1].

* I'd also rather not unwrap the:

    active     = models.NullBooleanField(…

  line, to keep the source readable in 80-char-wide terminals.

* You've also still got a FIXME marker:

    TEMPLATE_STRING_IF_INVALID = 'XXX-unset-variable-XXX' # FIXME: get by importing settings

  Does importing settings not work or something?

* Setting up a test database is usualy done with fixtures [2,3], not
  your self._setUpSites() and similar.

* I'd rather drop the ‘assert’ statements and use the assert methods
  [4], which usually give good error messages out of the box (without
  us having to specify the error message).

* There are also some driveby changes that distract from the
  substantive changes.  For example:

    -            for person in persons:
    -                person.num_taught = \
    -                    person.task_set.filter(role__name='instructor').count()
    +            for p in persons:
    +                p.num_taught = \
    +                    p.task_set.filter(role__name='instructor').count()

[1]: https://docs.djangoproject.com/en/1.7/ref/models/instances/#django.db.models.Model.get_FOO_display
[2]: https://docs.djangoproject.com/en/1.7/topics/testing/tools/#topics-testing-fixtures
[3]: https://docs.djangoproject.com/en/1.7/howto/initial-data/#providing-initial-data-with-fixtures
[4]: https://docs.python.org/2/library/unittest.html#assert-methods

**Comment by sburns** [comment]
I'll piggyback on the good comments from @wking. Typically, I don't test the actual HTML of responses because front-end changes that don't otherwise the site can stop the test-suite from passing.

I think it's better to [test the context](https://docs.djangoproject.com/en/1.7/topics/testing/tools/#django.test.Response.context) of the response to make sure the view is passing the correct objects to the template.

**Comment by sburns** [comment]
Also, if you're expecting a redirect (e.g. the user isn't logged in and is trying to access a view that requires authentication), you can test the redirect chain with [`response.redirect_chain`](https://docs.djangoproject.com/en/1.7/topics/testing/tools/#django.test.Client.get)

**Comment by gvwilson** [comment]
> You've also still got a FIXME marker:
> TEMPLATE_STRING_IF_INVALID = 'XXX-unset-variable-XXX' # FIXME: get by importing settings
> Does importing settings not work or something?

`import settings` and `import ..settings` and variations thereon don't work - the settings.py file is actually in the `amy` sub-directory.  I don't want to munge the path before import - would be grateful for directions on how to do this correctly.

**Comment by gvwilson** [comment]
I've been bitten before by testing the context rather than the rendered HTML (graphic designer edited the latter, I was feeding it the right things, they weren't being displayed).

**Comment by sburns** [comment]
> import settings and import ..settings and variations thereon don't work - the settings.py file is actually in the amy sub-directory.

The organization of apps in projects has undergone turbulent changes but for the most part django apps, e.g. workshops, should be _next_ to settings.py, urls.py, etc. and under `amy`. Then you can `from amy import settings` or some amount of dots up wrt your place in the particular application.

But...assuming the `DJANGO_SETTINGS_MODULE` envvar is set (probably `amy.settings`), then `from django.conf import settings` will be a module w/ read-only attributes coming from `amy/settings.py`. So you should be able to:

```python
from django.conf import settings

bad_template_string = settings.TEMPLATE_STRING_IF_INVALID
```

**Comment by gvwilson** [comment]
I just tried:

 > from django.conf import settings

w/out luck.  How about we wait until #134, #139, and #140 land, then 
move 'workshops' to where it ought to be?

**Comment by sburns** [comment]
> then move 'workshops' to where it ought to be?

agreed.

**Comment by sburns** [comment]
> w/out luck.  

There isn't a setup.py file but i wonder if python setup.py develop would fix this...symlinks the package into your environment so it's both installed and editable. </curiousity>

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 11:26:10AM -0800, Greg Wilson wrote:
> > You've also still got a FIXME marker:
> > TEMPLATE_STRING_IF_INVALID = 'XXX-unset-variable-XXX' # FIXME: get by importing settings
> > Does importing settings not work or something?
> 
> `import settings` and `import ..settings` and variations thereon
> don't work - the settings.py file is actually in the `amy`
> sub-directory.  I don't want to munge the path before import - would
> be grateful for directions on how to do this correctly.

Use [1]:

from django.conf import settings

[1]: https://docs.djangoproject.com/en/1.7/topics/settings/#using-settings-in-python-code

**Comment by gvwilson** [comment]
Tried that - didn't work.

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 12:52:49PM -0800, Scott Burns wrote:
> > w/out luck.  
> 
> There isn't a setup.py file…

You only need that if you're installing amy, and I don't think we need
that (running it out of a Git checkout should be fine).

Of course, I'd be fine if we wanted to package up the workshops app
for PyPI, and then have an amy repository with the minimal amy-app
boilerplate that we have now consuming the independent workshops app.
That's probably more work than we want for stage 1 though ;).

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 01:28:34PM -0800, Greg Wilson wrote:
> Tried that - didn't work.

More information would make it easier to debug ;).  What did you try?
How did you launch the tests?  How did they fail?

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 12:41:19PM -0800, Scott Burns wrote:
> The organization of apps in projects has undergone turbulent changes
> but for the most part django apps, e.g. workshops, should be _next_
> to settings.py, urls.py, etc. and under `amy`.

Hmm.  So long as workshops is in the PYTHONPATH (e.g. you're running
./manage.py from amy's root) it shouldn't matter where workshops is
located.  For example, it could be installed in your system's
site-packages (if we distributed the workshops package as a separate
project).  Importing the django project's settings file directly
(instead of using django.conf.settings) is breaks down the (useful)
wall between the app (workshops) and the site (amy).

**Comment by gvwilson** [comment]
> > There isn't a setup.py file…
> That's probably more work than we want for stage 1 though ;).
Agreed - Version 2.

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 01:39:13PM -0800, W. Trevor King wrote:
> Tue, Jan 20, 2015 at 01:28:34PM -0800, Greg Wilson:
> > Tried that - didn't work.
> 
> More information would make it easier to debug ;).  What did you try?
> How did you launch the tests?  How did they fail?

And after some Python 3 fixes, it's working for me (gvwilson/amy#12).

**Comment by gvwilson** [comment]
import settings

import ..settings

import ..amy.settings

from ..amy import settings

from django.conf import settings

all failed for me when using `make test` to run tests

**Comment by gvwilson** [comment]
OK, that works:

from django.config import settings

then using

settings.TEMPLATE_STRING_IF_INVALID

I'll add this to my PR and worry about "import .base" later.  (I presume 
the '.' to be sure you're importing from same directory rather than from 
elsewhere on path?)

**Comment by gvwilson** [comment]
p.s. thanks

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 02:34:28PM -0800, Greg Wilson wrote:
> from django.conf import settings
> 
> all failed for me when using `make test` to run tests

On my system, ‘python’ means ‘python3.3’, and I only have Django
installed for 3.4.  If I edit the Makefile to use ‘python3.4’ instead
of ‘python’, and use my adjusted branch (which uses the django.conf
line you mention, gvwilson/amy#12), I get:

  $ make test
  python3.4 manage.py test
  …
	Ran 32 tests in 2.390s

  OK
  Destroying test database for alias 'default'...

So can you give more information about what you're seeing than
“failed”?  Do you see an ImportError traceback?  What does it say?

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 02:39:36PM -0800, Greg Wilson wrote:
> OK, that works:
> 
> from django.config import settings
> 
> then using
> 
> settings.TEMPLATE_STRING_IF_INVALID
> 
> I'll add this to my PR…

Or just merge the first commit in my gvwilson/amy#12.

> and worry about "import .base" later.  (I presume the '.' to be sure
> you're importing from same directory rather than from elsewhere on
> path?)

Yes.  For details on relative imports see [1].  Perhaps we could
discuss any issues you have with gvwilson/amy#12 there?  Putting it
off just leaves this branch broken for Python 3 and makes more work
for me later if I have to rebase the branch to apply to some future
amy version.

[1]: https://www.python.org/dev/peps/pep-0328

**Pull request merged**
