### PR TITLE
Poor man's DataTables (ie. filters)

### LINKED ISSUE #129: DataTables for quick in-table search
In the past I have had a lot of success using [DataTables](http://www.datatables.net) to enhance HTML tables with search, column sorting, etc.

DataTable

It's a pretty quick, lightweight change and could complement the simple SQL search that currently exists in amy.  Would this be worth implementing?

### LINKED ISSUE #256: Filter workshops by organizing institution
@gperu would like to be able to filter workshops by the organizing institution (i.e., find all those being organized by SSI).

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
Resolves #256.
Resolves #129.

Work in progress: fix for #189, filters for other models (Airport, Task).

Changes:
* formerly invisible relationship between persons and their badges is now explicit (similar should be done for future person↔lesson relationship)
* new fluid (ie. width=100%) view
* filtering added for Event, Site, Person list views

Preview:
screen shot 2015-06-16 at 11 19 38

Please pull it down and try yourself and tell me what you think.

Thanks,
Piotr

### CODE REVIEW

**Comment by gvwilson** [comment]
Teaching today, will try to check it out tonight or tomorrow morning - thanks.

**Comment by gvwilson** [comment]
Just tried it out - there are lots of layout issues, but the functionality seems to be there for viewing events.

1. The filter menu appears above the table itself, even at very small resolution:

screen shot 2015-06-16 at 12 08 01 pm

2. The Amy logo is covered up on the dashboard page:

screen shot 2015-06-16 at 12 08 24 pm

But yeah, this will be very useful - please keep going.

**Comment by pbanaszkiewicz** [comment]
@gvwilson try hard refresh, you seem to have outdated styles.

**Comment by gvwilson** [comment]
Yup, that was it - thanks.

On 2015-06-16 12:10 PM, Piotr Banaszkiewicz wrote:
>
> @gvwilson <https://github.com/gvwilson> try hard refresh, you seem to 
> have outdated styles.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/pull/367#issuecomment-112482017>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by gvwilson** [comment]
How do I remove a filter that I've added? Clicking on 'Instructor' again doesn't do it.
screen shot 2015-06-16 at 12 58 33 pm

**Comment by pbanaszkiewicz** [comment]
@gvwilson I use "Ctrl" to multi-select and deselect items on lists like this. Not sure what does behave like this on Mac (command?).

**Comment by gvwilson** [comment]
Hm - I expected selecting a highlighted item to unselect it.

**Comment by pbanaszkiewicz** [comment]
Okay, I'm awating feedback.

**Comment by pbanaszkiewicz** [comment]
@gvwilson can you provide me with feedback on this?

**Comment by gvwilson** [comment]
This is really useful and should be merged - I'm still thrown off by the whole "how do I unclick?" thing, but that's me not knowing how to use my Mac.
:+1:

**Comment by pbanaszkiewicz** [comment]
I found one usability bug with our current approach regarding pagination. I'll submit a PR for that soon.

**Pull request merged**
