### PR TITLE
Case-insensitive matching of email

### LINKED ISSUE #226: Bulk-upload: New User added even in case of existing user
According to #225 , If a existing user with case insensitive email Id is uploaded with a new task, a new user is being added with that case insensitive email and no task is being added to the existing user.

### PR DESCRIPTION
**Pull request by darshan95**
This commit resolves #226 

create_uploaded_persons_tasks function was required to match email case-insensitive before creating a new person

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Good stuff. Thanks @darshan95 for the fix :)

**Comment by wking** [comment]
GitHub lost another of my mails ;).

**Comment by darshan95** [comment]
@wking updated the code

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 10:52:30AM -0700, Darshan Agarwal wrote:
> @wking updated the code

Looks good to me, thanks.

**Comment by pbanaszkiewicz** [comment]
Based on the feedback from @wking, I'm merging this one.

**Pull request merged**
