### PR TITLE
Speedup 2x tests

### PR DESCRIPTION
**Pull request by chrismedrela**
On my machine, this patch speedup tests execution from 90 seconds to 50 secs.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Whaaaaat. What improvement are you seeing? What do Django folks say about switching the hasher for tests?

**Comment by chrismedrela** [comment]
With this patch, it doesn't take so long to run tests. From my point of view, this is an improvement. :)

Switching hasher for tests is a tip from [Django doc](https://docs.djangoproject.com/en/1.9/topics/testing/overview/#speeding-up-the-tests).

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, could we merge this with the next release? This'll make my life much easier.

**Comment by pbanaszkiewicz** [comment]
I'm going to merge it soon, just let me test it first.

**Comment by pbanaszkiewicz** [comment]
Indeed this brings decent speedup: 27s vs 17s for me.

Merging with single change (comment about that conditional in the settings).

@chrismedrela If you want further speed up the tests, you can try the new multithreaded mode available since Django v1.9 I believe.

Thanks for this contribution!

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, do you mean executing `python3 manage.py test --parallel=4`? On my machine, I get `NotImplementedError: subtests aren't supported at this time` error from `multiprocessing` library.

**Comment by pbanaszkiewicz** [comment]
@chrismedrela yes, but I didn't claim it was painless :-)

**Comment by narayanaditya95** [comment]
Tests now throw segmentation fault everytime.

**Pull request merged**
